version: '3.6'

services:

  netcheck-frontend:
    container_name: netcheck-frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "80:80"

volumes:
  db-data:
    driver: local
