on: [push]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  release:
    name: Publish Github Release
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
      - name: Install Quasar globally
        run: yarn global add @quasar/cli
      - name: Install dependencies
        run: yarn
      - name: Build and package to zip
        run: echo "VERSION=`cat version.txt`" >> .env && quasar build && mkdir zip && cd dist/spa/ && zip -r ../../zip/release.zip .
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Publish Release on GitHub
        run: |
          go get github.com/tcnksm/ghr
          ghr -t ${{ secrets.GITHUB_TOKEN }} -u ${GITHUB_ACTOR} -r ${{ github.event.repository.name }} -c ${GITHUB_SHA} -delete `cat ./version.txt` ./zip/
